name: Belajar CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Skip test
        run: echo "Testing dilewati karena project belum memiliki script test"

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ziyauny

      - name: Build Docker image
        run: docker build -t ghcr.io/ziyauny/belajar-cicd-ubuntu:latest .

      - name: Push Docker image
        run: docker push ghcr.io/ziyauny/belajar-cicd-ubuntu:latest
