name: Belajar CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Skip test
        run: echo "Testing dilewati karena project belum memiliki script test"

      - name: Build Docker image
        run: docker build -t belajar-cicd:1.0 .
